"use strict";

module.exports = {
  BodyOfDocument: require('./BodyOfDocument'),
  ChangedPageFavicon: require('./ChangedPageFavicon'),
  ChangedPageTitle: require('./ChangedPageTitle'),
  CreatedDocumentFragmentWithAttributes: require('./CreatedDocumentFragmentWithAttributes'),
  DisabledElement: require('./DisabledElement'),
  DisabledElements: require('./DisabledElements'),
  ElementWithAdditionalHTML: require('./ElementWithAdditionalHTML'),
  ElementWithChangedValue: require('./ElementWithChangedValue'),
  ElementWithInnerHTML: require('./ElementWithInnerHTML'),
  ElementWithMappedObject: require('./ElementWithMappedObject'),
  ElementWithTextContent: require('./ElementWithTextContent'),
  ElementsWithToggledClass: require('./ElementsWithToggledClass'),
  EnabledElement: require('./EnabledElement'),
  EnabledElements: require('./EnabledElements'),
  ExtractedDocument: require('./ExtractedDocument'),
  FaviconOfDocument: require('./FaviconOfDocument'),
  FirstParsedElmSelector: require('./FirstParsedElmSelector'),
  HiddenElement: require('./HiddenElement'),
  HiddenElements: require('./HiddenElements'),
  ParsedElmSelectors: require('./ParsedElmSelectors'),
  PreparedProgressBar: require('./PreparedProgressBar'),
  PreparedProgressBars: require('./PreparedProgressBars'),
  ReplacedElementWithAnotherOne: require('./ReplacedElementWithAnotherOne'),
  ShownElement: require('./ShownElement'),
  ShownElements: require('./ShownElements'),
  TitleOfDocument: require('./TitleOfDocument'),
  UnwrappedChildrenOfParent: require('./UnwrappedChildrenOfParent'),
  UnwrappedTemplate: require('./UnwrappedTemplate')
};
